name: Run UI Tests

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]
    paths:
      - 'Sources/**'
      - '!Sources/Runestone/Documentation.docc/**'
      - 'Example/ExampleUITests/**'

jobs:
  build:
    name: Run tests
    runs-on: macOS-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run script
        run: bash Scripts/run-ui-tests.sh
